# Generated-by: Cursor (claude-4-sonnet)
name: Format Check

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Check code formatting
      run: |
        # Run format to see if any changes are needed
        make format
        
        # Check if any files were modified
        if ! git diff --exit-code; then
          echo "❌ Code formatting changes required!"
          echo "Please run 'make format' locally and commit the changes."
          echo ""
          echo "Files that need formatting:"
          git diff --name-only
          exit 1
        fi
        
        echo "✅ Code formatting is correct"